//./src/utils/pilotJobs.ts
// NOTE: This file is automatically created by ./db/convert_pilotAllowedCSV_to_tsDefinition.py
// Any changes made to this file may be overwritten by that script

export const jobsInPilotAllowed = [
    {"jobtype": "Art-Direktor/-in", "pilot_allowed": false},
    {"jobtype": "Arzt/Ärztin", "pilot_allowed": false},
    {"jobtype": "Bauleiter/-in", "pilot_allowed": false},
    {"jobtype": "Buchhalter/-in", "pilot_allowed": false},
    {"jobtype": "Account-Manager/-in", "pilot_allowed": true},
    {"jobtype": "Altenpflegehelfer/-in", "pilot_allowed": true},
    {"jobtype": "Altenpfleger/-in", "pilot_allowed": true},
    {"jobtype": "Arzthelfer/-in", "pilot_allowed": true},
    {"jobtype": "Augenoptiker/-in", "pilot_allowed": true},
    {"jobtype": "Bäcker/-in", "pilot_allowed": true},
    {"jobtype": "Bahnarbeiter/-in", "pilot_allowed": true},
    {"jobtype": "Bankkaufmann/-frau", "pilot_allowed": true},
    {"jobtype": "Barista", "pilot_allowed": true},
    {"jobtype": "Barkeeper/-in", "pilot_allowed": true},
    {"jobtype": "Bauhelfer/-in", "pilot_allowed": true},
    {"jobtype": "Bauzeichner/-in", "pilot_allowed": true},
    {"jobtype": "Berufsfeuerwehrmann/-frau", "pilot_allowed": true},
    {"jobtype": "Berufskraftfahrer/-in", "pilot_allowed": true},
    {"jobtype": "Business-Analyst/-in", "pilot_allowed": false},
    {"jobtype": "Bestatter/-in", "pilot_allowed": true},
    {"jobtype": "Betreuungskraft / Alltagsbegleiter/-in", "pilot_allowed": true},
    {"jobtype": "Betriebsleiter/-in", "pilot_allowed": true},
    {"jobtype": "Brief und Paketzusteller/-in", "pilot_allowed": true},
    {"jobtype": "Bürokaufmann/-frau", "pilot_allowed": true},
    {"jobtype": "Business Coach/-in", "pilot_allowed": true},
    {"jobtype": "Business-Development-Manager/-in", "pilot_allowed": true},
    {"jobtype": "Callcenter-Agent/-in", "pilot_allowed": true},
    {"jobtype": "Content-Manager/-in", "pilot_allowed": true},
    {"jobtype": "Einkäufer/-in", "pilot_allowed": true},
    {"jobtype": "Chef de Rang", "pilot_allowed": false},
    {"jobtype": "Einzelhandelskaufmann/-frau", "pilot_allowed": true},
    {"jobtype": "Elektriker/-in", "pilot_allowed": true},
    {"jobtype": "Elektroniker/-in", "pilot_allowed": true},
    {"jobtype": "Controller/-in", "pilot_allowed": false},
    {"jobtype": "Dekorateur/-in", "pilot_allowed": false},
    {"jobtype": "Eventmanager/-in", "pilot_allowed": true},
    {"jobtype": "Filialleiter/-in", "pilot_allowed": true},
    {"jobtype": "Fitnesstrainer/-in", "pilot_allowed": true},
    {"jobtype": "Flugbegleiter/-in", "pilot_allowed": true},
    {"jobtype": "Fotograf/-in", "pilot_allowed": true},
    {"jobtype": "Frisör/-in", "pilot_allowed": true},
    {"jobtype": "Fußballtrainer/-in", "pilot_allowed": true},
    {"jobtype": "Gärtner/-in", "pilot_allowed": true},
    {"jobtype": "Geschäftsführer/-in", "pilot_allowed": true},
    {"jobtype": "EDV-Techniker/-in", "pilot_allowed": false},
    {"jobtype": "Grafikdesigner/-in", "pilot_allowed": true},
    {"jobtype": "Handwerker/-in", "pilot_allowed": true},
    {"jobtype": "Haushälter/-in", "pilot_allowed": true},
    {"jobtype": "Ernährungsberater/-in", "pilot_allowed": false},
    {"jobtype": "Hausmeister/-in", "pilot_allowed": true},
    {"jobtype": "Haustechniker/-in", "pilot_allowed": true},
    {"jobtype": "Host/Hostess", "pilot_allowed": true},
    {"jobtype": "Erzieher/-in", "pilot_allowed": false},
    {"jobtype": "Hotelfachmann/-frau", "pilot_allowed": true},
    {"jobtype": "HR-Manager/-in", "pilot_allowed": true},
    {"jobtype": "Immobilienkaufmann/-frau", "pilot_allowed": true},
    {"jobtype": "Industriekaufmann/-frau", "pilot_allowed": true},
    {"jobtype": "IT-Administrator/-in", "pilot_allowed": true},
    {"jobtype": "Kassierer/-in", "pilot_allowed": true},
    {"jobtype": "Fahrdienstleiter/-in", "pilot_allowed": false},
    {"jobtype": "Koch/Köchin", "pilot_allowed": true},
    {"jobtype": "Kosmetiker/-in", "pilot_allowed": true},
    {"jobtype": "Finance-Manager/-in", "pilot_allowed": false},
    {"jobtype": "Florist/-in", "pilot_allowed": false},
    {"jobtype": "Krankenpflegehelfer/-in", "pilot_allowed": true},
    {"jobtype": "Krankenschwester/-pfleger", "pilot_allowed": true},
    {"jobtype": "Gleisbauer/-in", "pilot_allowed": false},
    {"jobtype": "Küchenhilfe", "pilot_allowed": true},
    {"jobtype": "Kundenberater/-in", "pilot_allowed": true},
    {"jobtype": "Kundenservice", "pilot_allowed": true},
    {"jobtype": "Head of Finance", "pilot_allowed": false},
    {"jobtype": "Lagermitarbeiter/-in", "pilot_allowed": true},
    {"jobtype": "Landwirt/-in", "pilot_allowed": true},
    {"jobtype": "Lehrer/-in", "pilot_allowed": true},
    {"jobtype": "Informatiker/-in", "pilot_allowed": false},
    {"jobtype": "Lieferfahrer/-in", "pilot_allowed": true},
    {"jobtype": "Lokführer/-in", "pilot_allowed": true},
    {"jobtype": "Ingenieur/-in", "pilot_allowed": false},
    {"jobtype": "Lufttransportbegleiter/-in", "pilot_allowed": true},
    {"jobtype": "Management-Assistent/-in", "pilot_allowed": true},
    {"jobtype": "Marketing-Manager/-in", "pilot_allowed": true},
    {"jobtype": "Maschinenführer/-in", "pilot_allowed": true},
    {"jobtype": "Mechaniker/-in", "pilot_allowed": true},
    {"jobtype": "Jurist/-in", "pilot_allowed": false},
    {"jobtype": "Medizinisches Personal", "pilot_allowed": true},
    {"jobtype": "Laborassistent/-in", "pilot_allowed": false},
    {"jobtype": "Mechatroniker/-in", "pilot_allowed": false},
    {"jobtype": "Meinungsforscher/-in", "pilot_allowed": true},
    {"jobtype": "Metzger/-in", "pilot_allowed": true},
    {"jobtype": "Möbelpacker/-in", "pilot_allowed": true},
    {"jobtype": "Mode Designer/-in", "pilot_allowed": true},
    {"jobtype": "Monteur/-in", "pilot_allowed": true},
    {"jobtype": "Müllwerker/-in", "pilot_allowed": true},
    {"jobtype": "Pädagoge/-in", "pilot_allowed": false},
    {"jobtype": "Objektmanager/-in", "pilot_allowed": true},
    {"jobtype": "Pharmazeut/-in", "pilot_allowed": false},
    {"jobtype": "Physiotherapeut/-in", "pilot_allowed": false},
    {"jobtype": "Produktmanager/-in", "pilot_allowed": false},
    {"jobtype": "Projektmanager/-in", "pilot_allowed": false},
    {"jobtype": "Office Manager/-in", "pilot_allowed": true},
    {"jobtype": "Psychologe/Psychologin", "pilot_allowed": false},
    {"jobtype": "Pflegekraft", "pilot_allowed": true},
    {"jobtype": "Pförtner/-in", "pilot_allowed": true},
    {"jobtype": "Portier/-in", "pilot_allowed": true},
    {"jobtype": "Produktionsmitarbeiter/-in", "pilot_allowed": true},
    {"jobtype": "Promoter/-in", "pilot_allowed": true},
    {"jobtype": "Regalauffüller/-in", "pilot_allowed": true},
    {"jobtype": "Reinigungskraft", "pilot_allowed": true},
    {"jobtype": "Qualitätssicherung", "pilot_allowed": false},
    {"jobtype": "Reiseleiter/-in", "pilot_allowed": true},
    {"jobtype": "Schneider/-in", "pilot_allowed": false},
    {"jobtype": "Reiseverkehrskaufmann/-frau", "pilot_allowed": true},
    {"jobtype": "Schweißer/-in", "pilot_allowed": false},
    {"jobtype": "Softwareentwickler/-in", "pilot_allowed": false},
    {"jobtype": "Reservierungsmitarbeiter/-in", "pilot_allowed": true},
    {"jobtype": "Restaurantleiter/-in", "pilot_allowed": true},
    {"jobtype": "Rettungssanitäter/-in", "pilot_allowed": true},
    {"jobtype": "Rezeptionist/-in", "pilot_allowed": true},
    {"jobtype": "Sachbearbeiter/-in", "pilot_allowed": true},
    {"jobtype": "Sales-Manager/-in", "pilot_allowed": true},
    {"jobtype": "Schichtleiter/-in", "pilot_allowed": true},
    {"jobtype": "Sozialarbeiter/-in", "pilot_allowed": false},
    {"jobtype": "Teamleiter/-in (IT)", "pilot_allowed": false},
    {"jobtype": "Übersetzer/-in", "pilot_allowed": false},
    {"jobtype": "Schlosser/-in", "pilot_allowed": true},
    {"jobtype": "Schreiner/-in", "pilot_allowed": true},
    {"jobtype": "Sekretär/-in", "pilot_allowed": true},
    {"jobtype": "Service/Kellner/-in", "pilot_allowed": true},
    {"jobtype": "Servicemitarbeiter/-in", "pilot_allowed": true},
    {"jobtype": "Sicherheitsmitarbeiter/-in", "pilot_allowed": true},
    {"jobtype": "Uhrmacher/-in", "pilot_allowed": false},
    {"jobtype": "Soldat/-in", "pilot_allowed": true},
    {"jobtype": "Speditionskaufmann/-frau", "pilot_allowed": true},
    {"jobtype": "Stellvertretender Restaurantleiter/-in", "pilot_allowed": true},
    {"jobtype": "Tagesmutter/-vater", "pilot_allowed": true},
    {"jobtype": "Tankwart/-in", "pilot_allowed": true},
    {"jobtype": "Unternehmensberater/-in", "pilot_allowed": false},
    {"jobtype": "Taxifahrer/-in", "pilot_allowed": true},
    {"jobtype": "Teamleiter/-in", "pilot_allowed": true},
    {"jobtype": "UX-Designer/-in", "pilot_allowed": false},
    {"jobtype": "Teamleiter/-in (Kundenservice)", "pilot_allowed": true},
    {"jobtype": "Teamleiter/-in (Sales)", "pilot_allowed": true},
    {"jobtype": "Techniker/-in", "pilot_allowed": true},
    {"jobtype": "Telefonist/-in", "pilot_allowed": true},
    {"jobtype": "Umzugshelfer/-in", "pilot_allowed": true},
    {"jobtype": "Verkäufer/-in", "pilot_allowed": true},
    {"jobtype": "Versicherungskaufmann/-frau", "pilot_allowed": true},
    {"jobtype": "Wirtschaftswissenschaftler/-in", "pilot_allowed": false},
    {"jobtype": "Versicherungsmathematiker/-in", "pilot_allowed": true},
    {"jobtype": "Vertriebler/-in", "pilot_allowed": true},
    {"jobtype": "Visagist/-in", "pilot_allowed": true},
    {"jobtype": "Zugbegleiter/-in", "pilot_allowed": true},
    {"jobtype": "Zusteller/-in", "pilot_allowed": true},
    {"jobtype": "Hebamme/Entbindungspfleger", "pilot_allowed": true},
    {"jobtype": "Polizist/-in", "pilot_allowed": true},
    {"jobtype": "Physiker/-in", "pilot_allowed": true},
    {"jobtype": "Handelsfachwirt/-in", "pilot_allowed": true},
];
